version: '3.8'
services:
  stats-service:
    build: ./stats-service/server
    image: stats-service
    container_name: stats-service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-server-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=iamroot

  stats-db:
    image: postgres:14.3-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats-server-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=iamroot

  main-service:
    build: ./main-service
    image: main-service
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-main-db
      - stats-service
    environment:
      - STATS_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-main-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-main-db:
    image: postgres:14.3-alpine
    container_name: ewm-main-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm-main-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
